import csv
from datetime import datetime
try:
    from reportlab.lib.pagesizes import letter
    from reportlab.pdfgen import canvas
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False

class ReportGenerator:
    """
    Generates PDF and CSV reports from scan histories.
    Uses reportlab for PDF creation and standard csv for CSVs.
    """

    @staticmethod
    def export_to_csv(filename: str, headers: list, data: list):
        """
        Generic CSV exporter.
        data is a list of lists or list of dicts.
        """
        try:
            with open(filename, 'w', newline='', encoding='utf-8') as f:
                writer = csv.writer(f)
                if headers:
                    writer.writerow(headers)
                for row in data:
                    if isinstance(row, dict):
                        # Extract row using headers as keys
                        writer.writerow([row.get(h, "") for h in headers])
                    else:
                        writer.writerow(row)
            return True, "Export successful."
        except Exception as e:
            return False, str(e)

    @staticmethod
    def generate_pdf_report(filename: str, title: str, summary: dict, items: list):
        """
        Generate a styled PDF report using ReportLab.
        summary is a dict of key metrics.
        items is a list of strings representing main findings.
        """
        if not REPORTLAB_AVAILABLE:
            return False, "ReportLab is not installed. PDF generation unavailable."

        try:
            c = canvas.Canvas(filename, pagesize=letter)
            width, height = letter
            
            # Title
            c.setFont("Helvetica-Bold", 24)
            c.drawString(50, height - 80, title)
            
            # Date
            c.setFont("Helvetica", 12)
            c.drawString(50, height - 100, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
            
            # Summary Section
            c.setFont("Helvetica-Bold", 16)
            c.drawString(50, height - 140, "Executive Summary")
            
            c.setFont("Helvetica", 12)
            y = height - 165
            for k, v in summary.items():
                c.drawString(60, y, f"{k}: {v}")
                y -= 25

            # Detailed Findings Section
            c.setFont("Helvetica-Bold", 16)
            y -= 20
            c.drawString(50, y, "Detailed Findings")
            
            c.setFont("Helvetica", 11)
            y -= 25
            for idx, item in enumerate(items, 1):
                if y < 50:
                    c.showPage()
                    y = height - 50
                    c.setFont("Helvetica", 11)
                
                c.drawString(60, y, f"{idx}. {item}")
                y -= 20

            # Footer
            c.setFont("Helvetica-Oblique", 10)
            c.drawString(50, 30, "Generated by CyberToolkit (Educational/Simulation Mode)")
            
            c.save()
            return True, "PDF Generated Successfully."
        except Exception as e:
            return False, str(e)
